#!/usr/bin/env bash
# Render /opt/m-dicail/.env from the current shell environment.
# Canonical env shape for Compose — used by GitHub Actions and Terraform local-exec.
#   export SECRET_KEY=... POSTGRES_USER=... && ./scripts/render-env.sh > .env
set -euo pipefail

: "${SECRET_KEY:?SECRET_KEY is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"

PORT="${PORT:-8000}"
AI_PORT="${AI_PORT:-8001}"
DOMAIN="${DOMAIN:-medicail.nf2.tech}"
if [[ "${DOMAIN}" == *".nf2.dev" ]]; then
  echo "[m-dicail-env] ERROR: DOMAIN=${DOMAIN} uses expired nf2.dev; set DOMAIN=medicail.nf2.tech" >&2
  exit 1
fi
ACCESS_TOKEN_TTL="${ACCESS_TOKEN_TTL:-1h}"
REFRESH_TOKEN_TTL_DAYS="${REFRESH_TOKEN_TTL_DAYS:-7}"
NCBI_API_KEY="${NCBI_API_KEY:-}"
NCBI_EMAIL="${NCBI_EMAIL:-}"
GROQ_API_KEY="${GROQ_API_KEY:-}"
GROQ_BASE_URL="${GROQ_BASE_URL:-https://api.groq.com/openai/v1}"
GROQ_TRANSCRIPTION_MODEL="${GROQ_TRANSCRIPTION_MODEL:-whisper-large-v3-turbo}"
GROQ_TIMEOUT_MS="${GROQ_TIMEOUT_MS:-120000}"
SMTP_HOST="${SMTP_HOST:-smtp.proton.me}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_USER="${SMTP_USER:-}"
SMTP_PASS="${SMTP_PASS:-}"
SMTP_FROM="${SMTP_FROM:-${SMTP_USER:-}}"
WEBAUTHN_RP_NAME="${WEBAUTHN_RP_NAME:-Medicail}"

APP_PUBLIC_URL="${APP_PUBLIC_URL:-https://${DOMAIN}}"
APP_DEEPLINK_SCHEME="${APP_DEEPLINK_SCHEME:-medicail}"
WEBAUTHN_RP_ID="${WEBAUTHN_RP_ID:-${DOMAIN}}"
WEBAUTHN_ORIGIN="${WEBAUTHN_ORIGIN:-https://${DOMAIN}}"
CORS_ORIGINS="${CORS_ORIGINS:-${APP_PUBLIC_URL}}"

cat <<EOF
PORT=${PORT}
AI_PORT=${AI_PORT}
NODE_ENV=production

SECRET_KEY=${SECRET_KEY}

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

NCBI_API_KEY=${NCBI_API_KEY}
NCBI_EMAIL=${NCBI_EMAIL}

# Groq STT for apps/ai (POC: post-recording enhance). Audio is sent to Groq.
GROQ_API_KEY=${GROQ_API_KEY}
GROQ_BASE_URL=${GROQ_BASE_URL}
GROQ_TRANSCRIPTION_MODEL=${GROQ_TRANSCRIPTION_MODEL}
GROQ_TIMEOUT_MS=${GROQ_TIMEOUT_MS}

ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
REFRESH_TOKEN_TTL_DAYS=${REFRESH_TOKEN_TTL_DAYS}

APP_PUBLIC_URL=${APP_PUBLIC_URL}
APP_DEEPLINK_SCHEME=${APP_DEEPLINK_SCHEME}
CORS_ORIGINS=${CORS_ORIGINS}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}

WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID}
WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME}
WEBAUTHN_ORIGIN=${WEBAUTHN_ORIGIN}
EOF
